### ISSUE TITLE
disable outline auto number ?

### ISSUE THREAD

**Issue by mydearxym** [CodeFalling/hexo-renderer-org#11]
can i remove this auto added number prefix ?

![image](https://cloud.githubusercontent.com/assets/6184465/14767188/5836c6b6-0a52-11e6-9388-d2bb8fcfcca0.png)

**Comment by CodeFalling** [comment]
Sure, just use
```
org:
  common: |
          #+OPTIONS: num: nil
```
in your `_config.yml`

**Comment by mydearxym** [comment]
thanks, consider put it in README.md
