### ISSUE TITLE
how to insert a image ?

### ISSUE THREAD

**Issue by mydearxym** [CodeFalling/hexo-renderer-org#12]
thanks for your work!

but i can't insert  image in  `source/images`

![image](https://cloud.githubusercontent.com/assets/6184465/14815948/e4f918f8-0be0-11e6-8568-30951a75024f.png)

in org file 

``` bash
[[/images/2016.04.25.23.53.jietu.png]]
``` 
renderr to 

![image](https://cloud.githubusercontent.com/assets/6184465/14816003/1f1de3ce-0be1-11e6-8a33-307f41cc3067.png)

the markdown syntax is not work either 

``` bash
![alt](/images/2016.04.25.23.53.jietu.png)
```

![image](https://cloud.githubusercontent.com/assets/6184465/14816188/08898478-0be2-11e6-9cbb-a5d9f342d46a.png)

and i use the latest version of `hexo-renderer-org`

**Comment by lengyueyang** [comment]
dont't add "/" before the dir, it's should be [[file:image/2016.04.25.23.53.jietu.png]], you could have a try.

**Comment by CodeFalling** [comment]
@lengyueyang thanks

@mydearxym Try @lengyueyang's way with https://github.com/CodeFalling/hexo-asset-image

**Comment by mydearxym** [comment]
@lengyueyang  @CodeFalling  thanks!  
i forgot  to add `file:` prefix
