### ISSUE TITLE
Read More not work

### ISSUE THREAD

**Issue by mydearxym** [CodeFalling/hexo-renderer-org#13]
![image](https://cloud.githubusercontent.com/assets/6184465/14824859/0e83ba88-0c0a-11e6-9e7b-e9b3dd971fd5.png)

render as 

![image](https://cloud.githubusercontent.com/assets/6184465/14824878/1eed8732-0c0a-11e6-9c64-bc6c14f36e4f.png)

**Comment by saccohuo** [comment]
U should use `#+BEGIN_XXX` and `#+END_XXX` in pairs, and in the two terms, `XXX` should be the same.
So you should correct the latter term to `#+END_HTML`.

**Comment by mydearxym** [comment]
can you show me a working code ? @saccohuo

**Comment by mydearxym** [comment]
thanks @saccohuo 
README is confused...
right version : 

#+BEGIN_HTML

#+END_HTML

**Comment by CodeFalling** [comment]
Opps, this is a typo in `README`..
