### ISSUE TITLE
how to set the footnotes style in config

### ISSUE THREAD

**Issue by Matrikslee** [CodeFalling/hexo-renderer-org#16]
the original style of footnotes is ugly( there is a new line between foot label and note content).

I read the html code and figure out that the footnote content is a `p` label in html and displayed in block atrribute.

I want to make them displayed in one line..

I insert `#+HTML_HEAD: <style>.footpara{ display:inline; }</style>` in org.common at _config.yml 
but this code is not placed to in exported html files. 
why?

**Comment by xfwduke** [comment]
it seems that emacs only pass html code to hexo without css.
you can add custom css into hexo theme.

`// Custom styles.
.footpara { display: inline-block; }
div.footdef > p {display: inline-block;}%`
