### ISSUE TITLE
建议采用org-mode-parser

### ISSUE THREAD

**Issue by wolfand11** [CodeFalling/hexo-renderer-org#25]
目前renderer使用了emacs来将org文件转换为html。
在hexo.extend.filter.register('before_post_render',   函数里面修改了data.content后是不会修改博客内容的。我看了一下emacs的参数，是不支持直接传递字符串的，所以传递data.content给emacs不好实现。
建议修改实现，可以采用org-mode-parser来导出data.content为html。
org-mode-parser的地址：https://github.com/daitangio/org-mode-parser/blob/master/test/to-html-test.js

**Comment by CodeFalling** [comment]
之前有试过org-mode-parser，或者说第一个版本就是。但是效果其实不是很好，而且 orgmode 变动过于频繁，直接用 emacs 带的 org=mode 可能是比较现实的方案了。或者有人来长期跟进维护 js 版本。
