### ISSUE TITLE
org里面的中文使用hexo g生成的html文件全部变成&#x5F88;这种utf8编码了

### ISSUE THREAD

**Issue by yyangdid** [CodeFalling/hexo-renderer-org#37]
如标题，除了title在生成的html里面是原装的中文，org的正文部分在 `hexo g` 生成的html文件里全部变成了类似 `&#x5F88;` 这种utf8编码了，直接使用 `emacs export html` 就不会。当然使用浏览器打开html文件的时候又自动转换为中文了，对于正常阅读没有什么大影响。
因为使用了 `hexo-generator-search` 插件作本地搜索， `hexo-generator-search` 生成的 `search.xml` 文件里面的中文情况和 `hexo-renderer-org` 生成html文件一样，这样在使用站内搜索的时候只能对标题进行中文搜索，正文里面的中文全部变成而 `&#x5F88;` 这种utf8编码了，搜索不了。 `.md` 就不会，中文就是中文。
所以我想是不是  `hexo-generator-search` 生成索引文件的时候会先用到 `hexo-generator-search` 解析，在解析的时候直接把中文转换为 `&#x5F88;` 了，我不懂nodejs，只是猜测，想让 @CodeFalling 闲暇时能给看看

系统：openSUSE42.2
系统语言：en_US   (切换为zh_CN也不行)
org使用spacemacs编写，文件编码是utf-8[unix]

最后感谢 @CodeFalling 写了两个很好用的插件 [`hexo-renderer-org`](https://github.com/CodeFalling/hexo-renderer-org) 和 [`hexo-asset-image` ](https://github.com/CodeFalling/hexo-asset-image)

**Comment by CodeFalling** [comment]
升级一下 hexo-renderer-org 和 hexo-asset-image 两个插件，他们都导致了这个问题，应该修掉了，感谢你的反馈😄

**Comment by yyangdid** [comment]
哇哦，速度好快，多谢多谢  ^v^
