### ISSUE TITLE
关于 fix #38

### ISSUE THREAD

**Issue by yyangdid** [CodeFalling/hexo-renderer-org#39]
我发现 #38 的问题后来 github看了一下，前几天已经修复，我升级了 `hexo-renderer-org` 模块，同时 `<` 不会解析为 `&lt;` 了，我这里 `clean` 了 ，解析为 `<;` 了，后面带了一个分号 `;` 。不知道是不是我的个例。
我升级模块到最新版本后，有些还是有点问题。
我简单测试了一下，好像和代码块的源码类型有关，我简单测试了下org-mode支持的代码类型，生成不太正常的大概分为三种：
+ `emacs-lisp` `lisp` 解析为：(`<` 解析为了 `<;`)
```
<;Command>
  <;Order>1</Order>
<;/Command>
```
+ `perl` 解析为：（有点混乱）
```
&lt;Command&gt;
  &lt;Order&gt;1&lt;/Order>
</Command&gt;
```
+ `asymptote` `dot` `gnuplot` `latex` `mscgen` `octave` `oz` `plantuml` `sed` `awk` `ditaa` `calc` `ledger` `lilypond` `org` `sass` `screen` `sqlite` 解析为：
```
&lt;Command&gt;
  &lt;Order&gt;1&lt;/Order&gt;
&lt;/Command&gt;
```
+ 其他语言解析正常

另求助下，有没有设置代码块显示行号的设置啊？按照 readme  里面设置没效果，我在hexo配置文件中开启和关闭代码块行号显示了都没效果。
在org文件插入代码块使用 `+n`  的方法倒是能显示行号，但是在网页中选择代码复制的时候也会把行号给选中复制了，希望选则代码块时不要选中行号。
行号的问题可能和 hexo-renderer-org 无关，只是都再用 hexo   所以顺带问一下 ^V^

**Comment by CodeFalling** [comment]
行号和此无关，按照配置开启后需要 theme 的支持（hexo 在这里完全只是个约定），你可以直接去参考对应 theme 的文档。

至于你提到的问题，很奇怪我在尝试修改 `test/org/simple-test.org` 后 `npm run test` 并没有重现你说的问题，你可以在测试中作为测试案例重现么？

**Comment by yyangdid** [comment]
我修改 `test/org/simple-test.org` 后 `npm run test` 也可以测试通过，没发现什么不对。
我把 `hexo-renderer-org` 恢复到 fix #38 之前一个版本，使用 `hexo g` 生成html文件观察了一下对于 `xml` 类型源码 `<Command>` 解析为这样：
```
<span class="line">&amp;lt;Command&amp;gt;</span>
```
`&amp;lt;` 是连贯的，在一个<span>里面。fix #38 之后直接把 `&amp;lt;` 替换为 `<` 了。

而对于 `emacs-lisp` 类型的源码 `(< a c)` 解析为这样：
```
<span class="list">(<span class="keyword">&amp;lt</span><span class="comment">; a c)</span></span>
```
`&amp;lt;` 是分别放在两个<span>里面，前一个放了 `&amp;lt` 后一个放了 `;` ，在fix #38 的替换语句里是不是把前一个<span>里面的 `&amp;lt` 替换为 `<` 了，第二个<span>还有个 `;` ，没得匹配了。
然后浏览器解析解析为 `(<; a c)` 了

不知道这个是不是emacs org-mode解析有问题

**Comment by frapples** [comment]
你说的这两个问题我已经修复了，提交了pull request。你需要重新从github上更新下你的hexo-renderer-org，然后清除下 hexo-org-cache目录下的缓存，hexo clean后重新生成就好了。
