### ISSUE TITLE
Line number not rendered properly

### ISSUE THREAD

**Issue by bcbcarl** [CodeFalling/hexo-renderer-org#50]
I just followed [this guide](https://github.com/CodeFalling/hexo-renderer-org#how-to-enable-line-number), restart hexo server and then update the org file, but line number not rendered in my code blocks. I also tried `line_number: false` but it doesn't works.

**Comment by CodeFalling** [comment]
`hexo-renderer-org` does not render line number in fact, you have to follow document of your **hexo theme** to find out how to enable line number.

**Comment by frapples** [comment]
@CodeFalling Old brother,  the bug isn't because of theme, the hexo config item is`highlight.line_number`, but you writed `highlight.number` in you code. I am fixing the bug.
