### ISSUE TITLE
Wrong type arguments

### ISSUE THREAD

**Issue by jack2gs** [CodeFalling/hexo-renderer-org#57]
Hi,

I tried the example given in the document. But failed, it reports:

> XXX==Error Here==>/Users/song/WorkStation/blog/jack2gs.github.io/source/_drafts/My-First-Blog-Post.org:
> Wrong type argument: listp, #("Hello,orgmode" 0 13 (:parent (#0)))
> (node:22131) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'parent' of null

Could anybody give me a hand?

**Environment**: macOS 10.12.5, GNU Emacs 25.2.1

Thanks,
Jack

**Comment by huangyingwen** [comment]
删除 emacs elpa ，包安装有问题
```
rm -rf ./.emacs.d/elpa
```
先不要打开 emacs ，直接运行 hexo server

**Comment by jack2gs** [comment]
问题已经解决，多谢！
