### ISSUE TITLE
Issue with org-file not begin with *...

### ISSUE THREAD

**Issue by allenwoods** [CodeFalling/hexo-renderer-org#8]
While org-file not begin with `*Title`， for example：
```org-mode
title: 使用Graphviz制作带数学公式的流程图
date: 2015-10-15 22:26:52
categories:
 - 技术
tags:
 - Graphviz
 - 编辑排版
---

Graphviz是个制作流程图的工具, 使用起来很方便. 美中不足的是不能在流程图中插公式.
借助ladot, 我们可以生成带公式的英文流程图.

#+BEGIN_HTML
<!--more-->
#+END_HTML

* Ladot+Graphviz
ladot支持直接在 =.dot= 文件中用 =Latex= 语法写公式, 比如
```
hexo will generate the web page from the `借助ladot, ` rather than from the real begining `Graphviz 是个制作流程图的工具...` 

It seems like it will generate from the second line, since if there is no line break between `...插公式.`
and `借助ladot`, page will be generated directly `*Ladot+Graphviz`

**Comment by CodeFalling** [comment]
Use `emacs` branch :laughing:
