### ISSUE TITLE
Issues with "ERROR Plugin load failed: hexo-renderer-org"

### ISSUE THREAD

**Issue by shellwjl** [CodeFalling/hexo-renderer-org#9]
![2016-01-10 15 15 03](https://cloud.githubusercontent.com/assets/13949779/12220450/f9a1bf54-b7ac-11e5-8262-e7537021d37e.png)
When I execute "hexo g",I got this problem
![2016-01-10 15 20 30](https://cloud.githubusercontent.com/assets/13949779/12220465/b7636a24-b7ad-11e5-87f6-1030a0cc3d00.png)

**Comment by CodeFalling** [comment]
You have to upgrade your nodejs.

**Comment by shellwjl** [comment]
I upgrade nodejs  v5.4.0
when i install this plugin,
I got : 
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN install Couldn't install optional dependency: Unsupported
Surprisingly, Hexo renderer plugin for emacs org-mode works successfully.

**Comment by CodeFalling** [comment]
This two `Unsupported` is *optional dependency* used by `hexo`.I got them,too and everything works well.

**Comment by xushaobo** [comment]
Yes,sorry for my late replay,I have solved by upgrade nodejs with the model named n，it is really easy to manage the version of nodejs.
Just like etc:
1: npm install -g n
2: n stable
or follow the version of node.js
2: n v0.10.26
